// MongoDB Playground
// Use Ctrl+Space inside a snippet or a string literal to trigger completions.

// The current database to use.
use('jobmilyo');

// Create a new document in the collection.
db.getCollection('postajobs').insertMany(
    [
        {
          "_id": ObjectId("66a768233620140000000000"),
          "jobtitle": "Data Scientist",
          "description": "Data Scientist needed for Himalayan Tech Labs",
          "qualification": "Bachelor's degree in Cloud solutions architect",
          "last_date": new Date("2024-12-16T14:27:54.151Z"),
          "company_logo": "https://res.cloudinary.com/dii2xg262/image/upload/v1721270450/jobmilyo/himalayantechlabs.jpg",
          "email": "hr@himalayantechlabs.com",
          "country": "Nepal",
          "number_of_post": 1,
          "experience": "4 years",
          "specialization_req": "JavaScript, React",
          "salary": "35k-45K",
          "company": "Himalayan Tech Labs",
          "rating": 5.0,
          "website_url": "himalayantechlabs.com",
          "address": "Chitwan",
          "state": "Bagmati",
          "user": ObjectId("668f69c2ebc31ae54779f9f3"),
          "site": "remote",
          "no_of_workingemployee": 145,
          "no_of_office": 1,
          "industry": "Information Technology",
          "interestedEmploymentTypes": "Part time",
          "no_vacancy": 1,
          "createdAt": new Date("2024-07-18T14:27:54.151Z"),
          "updatedAt": new Date("2024-07-18T14:27:54.151Z"),
          "__v": 0,
          "category": "cloud solutions architect"
        },
        {
          "_id": ObjectId("66a322943714635000000000"),
          "jobtitle": "Data Scientist",
          "description": "Data Scientist needed for Nepal Tech Solutions",
          "qualification": "Bachelor's degree in Full stack developer",
          "last_date": new Date("2024-10-05T14:27:54.151Z"),
          "company_logo": "https://res.cloudinary.com/dii2xg262/image/upload/v1721270450/jobmilyo/nepaltechsolutions.jpg",
          "email": "hr@nepaltechsolutions.com",
          "country": "Nepal",
          "number_of_post": 3,
          "experience": "2 years",
          "specialization_req": "AWS, Azure",
          "salary": "35k-45K",
          "company": "Nepal Tech Solutions",
          "rating": 4.3,
          "website_url": "nepaltechsolutions.com",
          "address": "Lalitpur",
          "state": "Lumbini",
          "user": ObjectId("668e00ae76b3245cbc554a0e"),
          "site": "remote",
          "no_of_workingemployee": 139,
          "no_of_office": 2,
          "industry": "Technology",
          "interestedEmploymentTypes": "Part time",
          "no_vacancy": 3,
          "createdAt": new Date("2024-07-18T14:27:54.151Z"),
          "updatedAt": new Date("2024-07-18T14:27:54.151Z"),
          "__v": 0,
          "category": "full stack developer"
        },
        {
          "_id": ObjectId("66a345909429778000000000"),
          "jobtitle": "Data Scientist",
          "description": "Data Scientist needed for Kathmandu Data Analytics",
          "qualification": "Bachelor's degree in Full stack developer",
          "last_date": new Date("2024-12-17T14:27:54.151Z"),
          "company_logo": "https://res.cloudinary.com/dii2xg262/image/upload/v1721270450/jobmilyo/kathmandudataanalytics.jpg",
          "email": "hr@kathmandudataanalytics.com",
          "country": "Nepal",
          "number_of_post": 3,
          "experience": "3 years",
          "specialization_req": "Python, R",
          "salary": "30k-40K",
          "company": "Kathmandu Data Analytics",
          "rating": 4.4,
          "website_url": "kathmandudataanalytics.com",
          "address": "Pokhara",
          "state": "Gandaki",
          "user": ObjectId("66980b7ca3fba5af7f44ddf7"),
          "site": "hybrid",
          "no_of_workingemployee": 184,
          "no_of_office": 5,
          "industry": "Technology",
          "interestedEmploymentTypes": "Full time",
          "no_vacancy": 3,
          "createdAt": new Date("2024-07-18T14:27:54.151Z"),
          "updatedAt": new Date("2024-07-18T14:27:54.151Z"),
          "__v": 0,
          "category": "full stack developer"
        },
        {
          "_id": ObjectId("66a503076267870000000000"),
          "jobtitle": "Cloud Solutions Architect",
          "description": "Cloud Solutions Architect needed for Nepal Tech Solutions",
          "qualification": "Bachelor's degree in Full stack developer",
          "last_date": new Date("2024-08-29T14:27:54.151Z"),
          "company_logo": "https://res.cloudinary.com/dii2xg262/image/upload/v1721270450/jobmilyo/nepaltechsolutions.jpg",
          "email": "hr@nepaltechsolutions.com",
          "country": "Nepal",
          "number_of_post": 2,
          "experience": "1 years",
          "specialization_req": "JavaScript, React",
          "salary": "30k-40K",
          "company": "Nepal Tech Solutions",
          "rating": 4.1,
          "website_url": "nepaltechsolutions.com",
          "address": "Lalitpur",
          "state": "Bagmati",
          "user": ObjectId("668e00ae76b3245cbc554a0e"),
          "site": "onsite",
          "no_of_workingemployee": 200,
          "no_of_office": 1,
          "industry": "Information Technology",
          "interestedEmploymentTypes": "Full time",
          "no_vacancy": 2,
          "createdAt": new Date("2024-07-18T14:27:54.151Z"),
          "updatedAt": new Date("2024-07-18T14:27:54.151Z"),
          "__v": 0,
          "category": "full stack developer"
        },
        {
          "_id": ObjectId("66a899614383769000000000"),
          "jobtitle": "Data Engineer",
          "description": "Data Engineer needed for Innovative AI Nepal",
          "qualification": "Bachelor's degree in Full stack developer",
          "last_date": new Date("2024-08-31T14:27:54.151Z"),
          "company_logo": "https://res.cloudinary.com/dii2xg262/image/upload/v1721270450/jobmilyo/innovativeainepal.jpg",
          "email": "hr@innovativeainepal.com",
          "country": "Nepal",
          "number_of_post": 2,
          "experience": "4 years",
          "specialization_req": "ETL, SQL",
          "salary": "25k-35K",
          "company": "Innovative AI Nepal",
          "rating": 4.0,
          "website_url": "innovativeainepal.com",
          "address": "Lalitpur",
          "state": "Lumbini",
          "user": ObjectId("66980b7ca3fba5af7f44ddf7"),
          "site": "hybrid",
          "no_of_workingemployee": 111,
          "no_of_office": 1,
          "industry": "Technology",
          "interestedEmploymentTypes": "Full time",
          "no_vacancy": 2,
          "createdAt": new Date("2024-07-18T14:27:54.151Z"),
          "updatedAt": new Date("2024-07-18T14:27:54.151Z"),
          "__v": 0,
          "category": "full stack developer"
        },
        {
          "_id": ObjectId("66a929268121876000000000"),
          "jobtitle": "AI Engineer",
          "description": "AI Engineer needed for Nepal Tech Solutions",
          "qualification": "Bachelor's degree in Cloud solutions architect",
          "last_date": new Date("2024-12-11T14:27:54.151Z"),
          "company_logo": "https://res.cloudinary.com/dii2xg262/image/upload/v1721270450/jobmilyo/nepaltechsolutions.jpg",
          "email": "hr@nepaltechsolutions.com",
          "country": "Nepal",
          "number_of_post": 2,
          "experience": "1 years",
          "specialization_req": "ETL, SQL",
          "salary": "35k-45K",
          "company": "Nepal Tech Solutions",
          "rating": 4.4,
          "website_url": "nepaltechsolutions.com",
          "address": "Bhaktapur",
          "state": "Bagmati",
          "user": ObjectId("668e00ae76b3245cbc554a0e"),
          "site": "hybrid",
          "no_of_workingemployee": 200,
          "no_of_office": 2,
          "industry": "Information Technology",
          "interestedEmploymentTypes": "Part time",
          "no_vacancy": 2,
          "createdAt": new Date("2024-07-18T14:27:54.151Z"),
          "updatedAt": new Date("2024-07-18T14:27:54.151Z"),
          "__v": 0,
          "category": "cloud solutions architect"
        },
        {
          "_id": ObjectId("66a61762a370938000000000"),
          "jobtitle": "Data Engineer",
          "description": "Data Engineer needed for Kathmandu Data Analytics",
          "qualification": "Bachelor's degree in Cloud solutions architect",
          "last_date": new Date("2024-10-25T14:27:54.151Z"),
          "company_logo": "https://res.cloudinary.com/dii2xg262/image/upload/v1721270450/jobmilyo/kathmandudataanalytics.jpg",
          "email": "hr@kathmandudataanalytics.com",
          "country": "Nepal",
          "number_of_post": 1,
          "experience": "1 years",
          "specialization_req": "AWS, Azure",
          "salary": "30k-40K",
          "company": "Kathmandu Data Analytics",
          "rating": 4.2,
          "website_url": "kathmandudataanalytics.com",
          "address": "Lalitpur",
          "state": "Lumbini",
          "user": ObjectId("66980b7ca3fba5af7f44ddf7"),
          "site": "onsite",
          "no_of_workingemployee": 160,
          "no_of_office": 5,
          "industry": "Technology",
          "interestedEmploymentTypes": "Part time",
          "no_vacancy": 1,
          "createdAt": new Date("2024-07-18T14:27:54.151Z"),
          "updatedAt": new Date("2024-07-18T14:27:54.151Z"),
          "__v": 0,
          "category": "cloud solutions architect"
        }
    ]
);
