import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider"
import { Inter, Splash } from "next/font/google";
import "./globals.css";

import SplashScreen from "./components/SplashScreen";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Job Milyo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={inter.className}>
      
      
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <SplashScreen />
            <Navbar />
            {children}
          </ThemeProvider>
        </body>
    </html>
  );
}
